name: Keep Streamlit App Awake

on:
  schedule:
    # 💡 5시간 간격 실행 (24시간이 5로 안 떨어져서 마지막 텀은 4시간 간격으로 돕니다)
    # 한국 시간(KST) 기준: 09:00, 14:00, 19:00, 00:00, 05:00 실행
    # UTC 기준: 00:00, 05:00, 10:00, 15:00, 20:00
    - cron: '0 */5 * * *'
  workflow_dispatch: # 수동 실행 버튼 유지

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          # 💡 본(Main) 서버 깨우기
          curl -I "https://stockapp-sky.streamlit.app/"
          
          # 💡 Dev(개발) 서버 깨우기 (아래 주소를 실제 Dev 주소로 변경하세요)
          curl -I "https://stockapp-sky-dev.streamlit.app/"
